# Generated by Django 3.1.6 on 2021-02-10 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionLoggerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='address',
            field=models.TextField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='tel',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]{2,4}-[0-9]{2,4}-[0-9]{3,4}$')]),
        ),
    ]
