# Generated by Django 3.1.6 on 2021-02-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionLoggerApp', '0007_auto_20210210_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='userId',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
