# Generated by Django 3.1.6 on 2021-02-11 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionLoggerApp', '0008_auto_20210210_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='address',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='email',
            field=models.EmailField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='firstName',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='lastName',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]{2,4}-[0-9]{2,4}-[0-9]{3,4}$')]),
        ),
    ]
