# Generated by Django 3.1.6 on 2021-02-12 02:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionLoggerApp', '0014_auto_20210212_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='userId',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9-_]{4-10}$')]),
        ),
    ]
