# Generated by Django 3.1.6 on 2021-02-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionLoggerApp', '0015_auto_20210212_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='userId',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
