# Generated by Django 3.1.6 on 2021-02-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionLoggerApp', '0016_auto_20210212_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='firstName',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='lastName',
            field=models.CharField(max_length=15),
        ),
    ]
