# Generated by Django 3.1.6 on 2021-02-18 00:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('actionLoggerApp', '0019_actionlog_gohometime'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='submitTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
