# Generated by Django 3.1.6 on 2021-03-05 06:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actionLoggerApp', '0020_actionlog_submittime'),
    ]

    operations = [
        migrations.CreateModel(
            name='MgtGroup',
            fields=[
                ('groupId', models.CharField(max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9_]{8,12}$')])),
                ('groupName', models.CharField(max_length=30)),
                ('adminUserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
