# Generated by Django 3.1.6 on 2021-03-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionLoggerApp', '0021_mgtgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mgtgroup',
            name='groupId',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
