# Generated by Django 3.1.6 on 2021-03-12 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actionLoggerApp', '0022_auto_20210306_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='place',
            field=models.TextField(default='aaaa', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='reason',
            field=models.TextField(default='aaaa', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EntryGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actionLoggerApp.mgtgroup')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
